### ISSUE TITLE
Allow usage with native environment variable support

### ISSUE THREAD

**Issue by captncraig** [koenrh/dnscontrol-action#21]
Hey, it was awesome to see this action exists. 

I am not sure if you are aware, but dnscontrol supports environment variables natively in `creds.json`. It will already replace anything that looks like `$SOME_VAR` if it finds a matching env var.

[Here](https://github.com/captncraig/dns/blob/master/creds.json) is an example of how I set it up. For local dev I just have a `.env` file that I gitignore, and for CI I put the vars into secrets. I can check in the "template" creds.json, but still inject the values at runtime.

I could see this somewhat simplifying this action not needing to manage all possible env vars explicitly. But also breaking backward compatibility, since your current version will nuke anything in creds.json and people may be depending on how you set it up.

I've done that in [my fork](https://github.com/captncraig/dnscontrol-action) and it seems to work well. 

Thoughts?

**Comment by koenrh** [comment]
Hi @captncraig,

First of all, thank you for work on DNSControl!

If I'm being honest, I don't recall why I set it up the way I did. It might actually have been related to some limitations in the earlier versions of GitHub Actions (when I set it up). I will do some testing based on your suggestions using my personal projects that use DNSControl with this GitHub Action.

If that works there is also not really a need anymore to have a separate repository. What do you think of pulling this into the the DNSControl repository? It will be mostly documentation, examples, and the [Marketplace entry](https://github.com/marketplace/actions/dnscontrol-action). Happy to submit a pull request!
