### ISSUE TITLE
Link to this on dnscontrol?

### ISSUE THREAD

**Issue by tlimoncelli** [koenrh/dnscontrol-action#48]
Hey this GHA is really neat!

Would you like to link to it from the DNSControl README or other docs?

**Comment by koenrh** [comment]
Hey @tlimoncelli! Thank you for work on DNSControl and my apologies for the late reply. That would be cool. Happy to submit a PR.

**Comment by koenrh** [comment]
If you're open to it, I'm also happy to see if I could fold it into the [StackExchange/DNSControl](https://github.com/StackExchange/DNSControl) GitHub repository and publish it as an "official" GitHub Action and have it published to the GitHub Marketplace.

**Comment by tlimoncelli** [comment]
Hi there!

I appreciate the offer but I'd like to keep the GitHub actions in a separate repo for now.  I definitely want to link to your repo, however!  I look forward to the PR!

Tom

**Comment by Firefishy** [comment]
As a user of the action, it would be nice to see it move to "official" status at: https://github.com/StackExchange/DNSControl-action
