### ISSUE TITLE
Filter the "Pull request comment" output

### ISSUE THREAD

**Issue by tlimoncelli** [koenrh/dnscontrol-action#52]
If you have many domains, the comment posted to the PR is very long.  I've found it better if the GHA log shows all the output, but what gets posted as a comment is filtered heavily.

We use this script immediately after the `echo "$OUTPUT"` line. 

(this is from memory)

```
OUTPUT=$(echo "$OUTPUT" | bin/filter-preview.sh)
```

Here's the filter-preview.sh script:

```
$ cat bin/filter-preview.sh
#!/bin/bash

grep -v -e '\.\.\.0 corrections$' |\
  grep -v -e '\.\.\. (skipping)' |\
  grep -v -e '----- Getting nameservers from:'
```

* The multiple grep's can probably be combined
* It probably doesn't need to be a separate script, but it is easier to debug that way. It also permits me to use the script on the command line when I'm making changes outside of GHA.

**Comment by koenrh** [comment]
Yeah, noticed that as well. Good suggestion!

Quickly added something based on your suggestion in https://github.com/koenrh/dnscontrol-action/pull/57. Will do some testing later today.
