### ISSUE TITLE
Update to DNSControl v3.15.0?

### ISSUE THREAD

**Issue by wblondel** [koenrh/dnscontrol-action#66]
HI!

Thank you for your work.
An update to v3.15.0 would be great :)

Thanks!

**Comment by Firefishy** [comment]
Looks upstream hasn't yet released a docker container, latest is v3.13.0: https://hub.docker.com/r/stackexchange/dnscontrol/tags

**Comment by dschaper** [comment]
Looks like there may be a v3.14.0 at https://hub.docker.com/layers/dnscontrol/stackexchange/dnscontrol/v3.14.0/images/sha256-82c12ca4117348f62f15312c5d90b76a4707171f3ac5d789e7510f4549697cd1?context=explore

At least until upstream fixes what ever issue they have with releasing new docker images.

(https://hub.docker.com/r/jauderho/dnscontrol/tags is an up to date build if that's something to look at as well.)

**Comment by Firefishy** [comment]
> Looks like there may be a v3.14.0 at https://hub.docker.com/layers/dnscontrol/stackexchange/dnscontrol/v3.14.0/images/sha256-82c12ca4117348f62f15312c5d90b76a4707171f3ac5d789e7510f4549697cd1?context=explore
> 
> At least until upstream fixes what ever issue they have with releasing new docker images.
> 
> (https://hub.docker.com/r/jauderho/dnscontrol/tags is an up to date build if that's something to look at as well.)

Nice! And finally arm64 builds which I have been waiting for.  I hacked up my own pipeline for that: https://github.com/Firefishy/dnscontrol-docker

**Comment by koenrh** [comment]
Bumped to v3.16 in https://github.com/koenrh/dnscontrol-action/pull/69. Apologies for the delay!

**Comment by tlimoncelli** [comment]
3.16.0 has a minor bug with the "dnscontrol check" command.  3.16.1 will fix it.
