### ISSUE TITLE
Source for upstream container?

### ISSUE THREAD

**Issue by Firefishy** [koenrh/dnscontrol-action#67]
The `ghcr.io/koenrh/dnscontrol:v3.13.0@sha256:2e0ff54e609f418d285b776f3bbceee35b73eac8637731395e1a001ad7c38898` upstream container used by the `Dockerfile` doesn't seem to have any public github repo or build chain.

It would be great to have one. 

I have created https://github.com/Firefishy/dnscontrol-docker as an initial start (including github actions)

**Comment by Firefishy** [comment]
@koenrh Happy to reformat this if desired? I could also make this 2 stage (1st stage building via Go) to support multi-arch if desired.

Feel free to fork or clone the above repo. It will need minor image names amends.

**Comment by koenrh** [comment]
Yes, good point! The `Dockerfile` and the build process should definitely be public.

It was only meant as a temporary work-around, but it looks like there won't be an official Docker image published anymore. I prefer to use the official binaries as much as possible, so I might add a `Dockerfile` that just copies over the pre-built binary for Linux.

I'll have a look at the repository you linked as well. I like the idea of using GitHub Actions to build and publish the Docker image to the registry.

**Comment by koenrh** [comment]
Took inspiration from your repository, and simplified the `Dockerfile`. It removes the DNSControl base image and now uses an install stage where DNSControl is installed using `go install`. https://github.com/koenrh/dnscontrol-action/pull/69
