### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by georgejipa** [koenrh/dnscontrol-action#82]
Everything is working fine, but I'm getting the following warning:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by koenrh** [comment]
Fixed in https://github.com/koenrh/dnscontrol-action/pull/83. Thank you!
